### ISSUE TITLE
DeepL support

### ISSUE THREAD

**Issue by BlackBird-One** [xiles/XCStringsEditor#15]
Hi, thanks for a great app that really makes my work on localizations a lot easier. Since I prefer DeepL, I implemented its basic support in my fork. 
I'm using XCStringsEditor a lot right now, so I ran into a few minor issues. I fixed them right away and added an idea that uses reverse translation to help evaluate the quality of the translation. In connection with this, I have adjusted the filtering of the list.
You can find everything in my fork and you can take it over. I haven't contributed to the public git yet, so I don't know how to do it. If anything needs to be explained, I'll be happy to answer.
Sincerely, Michal Kus

**Comment by xiles** [comment]
Thanks for the contribution!
I added your sources to my repository to support DeepL. (some of them are modified a little bit)
