### ISSUE TITLE
Crashes when opening .xcstrings file 

### ISSUE THREAD

**Issue by warpling** [xiles/XCStringsEditor#19]
Submitted crash via macOS crash reporting
(file contains a couple languages, one with 0% translation progress)

**Comment by xiles** [comment]
Could you provide a sample .xcstrings file? 
The crash report via macOS crash reporting is not reaching me.

**Comment by ShlomoCode** [comment]
@xiles [Localizable.xcstrings.zip](https://github.com/user-attachments/files/16145325/Localizable.xcstrings.zip)
This file works with XCode and crashes with XCStringsEditor

**Comment by xiles** [comment]
@ShlomoCode thanks for the sample file to test. I tested with the latest source and the app doesn't crash.

**Comment by ShlomoCode** [comment]
Maybe it has been fixed already? I tested with https://github.com/xiles/XCStringsEditor/releases/tag/Release%2F0.9.0, I didn't compile from the source
Can you release an updated version?

**Comment by xiles** [comment]
Added a new release ver 0.9.1

**Comment by ShlomoCode** [comment]
I confirm that the new version of XCStringsEditor no longer crashes! :+1::+1:
